In [80]:
import pandas as pd

In [81]:
names = pd.read_csv("C:\\Users\\tsarcevic\\Downloads\\names.csv", names=['code', 'name'])

In [82]:
names

   code                                               name
0    X1                      Cost of Interest-bearing Debt
1    X2                            Cash Reinvestment Ratio
2    X3                                      Current Ratio
3    X4                                          Acid Test
4    X5                    Interest Expenses/Total Revenue
..  ...                                                ...
90  X91       Continuing Operating Income after Tax Growth
91  X92   Net Income-Excluding Disposal Gain or Loss Gr...
92  X93                                 Total Asset Growth
93  X94                                Total Equity Growth
94  X95                       Return on Total Asset Growth

[95 rows x 2 columns]

In [83]:
data = pd.read_csv("C:\\Users\\tsarcevic\\Downloads\\TEJ-Normalized_2013_0430_Taiwan_data.csv", delimiter=';')

In [84]:
data

,Flag,"ROA(C) Before tax, before interest, and before depreciation",ROA(A)% after tax,"ROA(B) After tax, before interest, before depreciation",Operating gross profit margin,Realized gross profit margin,Operating profit ratio,Net interest rate before tax,Net interest rate after tax,Non-industry revenue and expenditure / revenue,...,net income to total assets,total assets to GNP price,No-credit interval,Gross profit to Sales,Net income to stockholder's Equity,liability to equity,Degree of financial leverage (DFL),Interest coverage ratio( Interest expense to EBIT ),one if net income was negative for the last two year zero otherwise,equity to liability
0,1,"3,70594E+14","4,24389E+14","4,0575E+13","6,01457E+14","6,01457E+14","9,98969E+14","7,96887E+14","8,08809E+14","3,02646E+14",...,"7,16845E+14",0.009219,"6,22879E+14","6,01453E+14","8,2789E+13","2,90202E+13","2,66006E+14","5,6405E+14",1,"1,64687E+14"
1,1,"4,64291E+14","5,38214E+13","5,1673E+14","6,10235E+14","6,10235E+14","9,98946E+14","7,9738E+14","8,09301E+14","3,03556E+14",...,"7,95297E+14",0.008323,"6,23652E+14","6,10237E+14","8,39969E+14","2,83846E+14","2,64577E+14","5,70175E+14",1,"2,07943E+13"
2,1,"4,26071E+14","4,99019E+14","4,72295E+14","6,0145E+14","6,01364E+14","9,98857E+14","7,96403E+14","8,08388E+14","3,02035E+14",...,"7,7467E+14",0.040003,"6,23841E+14","6,01449E+14","8,36774E+14","2,90189E+14","2,65547E+14","5,63706E+14",1,"1,64741E+14"
3,1,"3,99844E+14","4,51265E+14","4,57733E+14","5,83541E+14","5,83541E+14","9,987E+14","7,96967E+14","8,08966E+14","3,0335E+14",...,"7,39555E+14",0.003252,"6,22929E+14","5,83538E+14","8,34697E+14","2,81721E+14","2,66966E+14","5,64663E+14",1,"2,39823E+14"
4,1,"4,65022E+14","5,38432E+14","5,22298E+14","5,98783E+14","5,98783E+14","9,98973E+14","7,97366E+14","8,09304E+14","3,03475E+14",...,"7,95016E+13",0.003878,"6,23521E+14","5,98782E+14","8,39973E+14","2,78514E+14","2,47518E+14","5,75617E+14",1,"3,54902E+14"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6814,0,"4,93687E+13","5,39468E+14","5,4323E+14","6,04455E+14","6,04462E+14","9,98992E+13","7,97409E+13","8,09331E+14","3,0351E+13",...,"7,99927E+14",0.000466,"6,2362E+13","6,04455E+14","8,40359E+14","2,79606E+13","2,70643E+14","5,66193E+14",1,"2,98901E+14"
6815,0,"4,75162E+14","5,38269E+14","5,24172E+14","5,98308E+14","5,98308E+14","9,98992E+14","7,97414E+14","8,09327E+14","3,0352E+14",...,"7,99748E+14",0.001959,"6,23931E+14","5,98306E+14","8,40306E+14","2,78132E+11","2,70086E+13","5,66018E+14",1,"3,82837E+14"
6816,0,"4,72725E+13","5,33744E+14","5,20638E+14","6,10444E+14","6,10213E+14","9,98984E+14","7,97401E+13","8,09317E+14",30351219939,...,"7,97778E+14",0.002840,"6,24156E+14","6,10441E+14","8,40138E+14","2,75789E+14","2,67912E+14","5,65158E+14",1,"9,76487E+14"
6817,0,"5,06264E+14","5,59911E+14","5,54045E+14","6,0785E+14","6,0785E+14","9,99074E+13","7,975E+14","8,09399E+14","3,03498E+14",...,"8,11808E+13",0.002837,"6,23957E+14","6,07846E+14","8,41084E+14","2,77547E+14","2,6822E+14","5,65302E+14",1,"4,40094E+14"
6818,0,"4,93053E+14","5,70105E+14","5,49548E+14","6,27409E+12","6,27409E+12","9,9808E+14","8,01987E+14","8,138E+14","3,13415E+14",...,"8,15956E+14",0.000707,"6,2668E+14","6,27408E+14","8,41019E+14","2,75114E+14","2,6793E+14","5,65167E+14",1,"2,33902E+14"

In [85]:
len(data.columns)

96

In [86]:
len(names)

95

In [22]:
# assuming the difference is the target column "Flag"

## Similarity modelling

1. find exact names
2. tba

In [87]:
def find_perfect_match(list1, list2):   # list1 is referred to as the one with original names
    perfect_matches = []
    unmatched1 = list1
    unmatched2 = list2
    for element in list1:
        original_name = element
        #preprocess
        element = element.strip().lower()
        print(original_name)
        print(element)
        for element2 in unmatched2:
            original2 = element2
            element2 = element2.strip().lower().strip()
            if element == 'liability to equity':
                print(element)
                print(element2)
            if element == element2:
                perfect_matches.append(original_name)
                unmatched1.remove(original_name)
                unmatched2.remove(original2)
                print('______________________________')
                break
    return perfect_matches, (unmatched1, unmatched2)

In [88]:
perfect_matches, (unmatched1, unmatched2) = find_perfect_match(list(names.name), list(data.columns))

 Cost of Interest-bearing Debt
cost of interest-bearing debt
 Cash Reinvestment Ratio
cash reinvestment ratio
 Current Ratio
current ratio
______________________________
 Interest Expenses/Total Revenue
interest expenses/total revenue
 Total Liability/Equity Ratio
total liability/equity ratio
 Liability/Total Assets
liability/total assets
 Interest-bearing Debt/Equity
interest-bearing debt/equity
 Contingent Liability/Equity
contingent liability/equity
 Operating Income/Capital
operating income/capital
 Pretax Income/Capital
pretax income/capital
 Working Capital to Total Assets
working capital to total assets
______________________________
 Current Assets/Total Assets
current assets/total assets
______________________________
 Quick Assets/Current Liability
quick assets/current liability
 Cash/Current Liability
cash/current liability
 Current Liability to Assets
current liability to assets
______________________________
 Inventory/Working Capital
inventory/working capital
______________________________
 Current Liabilities/Liability
current liabilities/liability
 Working Capital/Equity
working capital/equity
______________________________
 Long-term Liability to Current Assets
long-term liability to current assets
______________________________
 One if Total Liability exceeds Total Assets;
one if total liability exceeds total assets;
 Equity to Liability
equity to liability
______________________________
 (Long-term Liability+Equity)/Fixed Assets
(long-term liability+equity)/fixed assets
 Fixed Assets to Assets
fixed assets to assets
 Current Liability to Liability
current liability to liability
______________________________
 Equity to Long-term Liability
equity to long-term liability
______________________________
 Degree of Financial Leverage
degree of financial leverage
 Interest Coverage Ratio
interest coverage ratio
 Operating Expenses/Net Sales
operating expenses/net sales
 (Research and Development Expenses)/Net Sales
(research and development expenses)/net sales
 Effective Tax Rate
effective tax rate
 Book Value Per Share(B)
book value per share(b)
 Book Value Per Share(A)
book value per share(a)
 Book Value Per Share(C)
book value per share(c)
 Cash Flow Per Share
cash flow per share
______________________________
 Operating Income Per Share
operating income per share
 Sales Per Employee
sales per employee
 Operation Income Per Employee
operation income per employee
 Fixed Assets Per Employee
fixed assets per employee
 total assets to GNP price
total assets to gnp price
______________________________
 Return On Total Assets(A)
return on total assets(a)
 Return On Total Assets(B)
return on total assets(b)
 Gross Profit /Net Sales
gross profit /net sales
 Realized Gross Profit/Net Sales
realized gross profit/net sales
 Operating Income /Net Sales
operating income /net sales
 Pre-Tax Income/Net Sales
pre-tax income/net sales
 Net Income/Net Sales
net income/net sales
 Net Non-operating Income Ratio
net non-operating income ratio
 Net Income-Exclude Disposal Gain or Loss/Net Sales
net income-exclude disposal gain or loss/net sales
 EPS-Net Income
eps-net income
 Pretax Income Per Share
pretax income per share
 Retained Earnings to Total Assets
retained earnings to total assets
 Total Income to Total Expenses
total income to total expenses
 Total Expenses to Assets
total expenses to assets
 Net Income to Total Assets
net income to total assets
______________________________
 Net Income to Stockholder's Equity
net income to stockholder's equity
______________________________
 (Inventory +Accounts Receivables) /Equity
(inventory +accounts receivables) /equity
 Total Asset Turnover
total asset turnover
______________________________
 Days Receivable Outstanding
days receivable outstanding
 Inventory Turnover
inventory turnover
 Fixed Asset Turnover
fixed asset turnover
 Equity Turnover
equity turnover
 Current Assets to Sales
current assets to sales
 Quick Assets to Sales
quick assets to sales
 Working Capital to Sales
working capital to sales
______________________________
 Cash Flow to Sales
cash flow to sales
______________________________
 Cash Flow from Operating/Current Liabilities
cash flow from operating/current liabilities
 Cash Flow to Total Assets
cash flow to total assets
______________________________
 CFO to Assets
cfo to assets
______________________________
 Realized Gross Profit Growth Rate
realized gross profit growth rate
 Operating Income Growth
operating income growth
 Net Income Growth
net income growth
 Continuing Operating Income after Tax Growth
continuing operating income after tax growth
 Net Income-Excluding Disposal Gain or Loss Growth
net income-excluding disposal gain or loss growth
 Total Asset Growth
total asset growth
 Total Equity Growth
total equity growth
 Return on Total Asset Growth
return on total asset growth

In [89]:
len(perfect_matches)

19

In [90]:
len(unmatched1)

76

In [91]:
perfect_matches

[' Current Ratio',
 ' Working Capital to Total Assets',
 ' Current Assets/Total Assets',
 ' Current Liability to Assets',
 ' Inventory/Working Capital',
 ' Working Capital/Equity',
 ' Long-term Liability to Current Assets',
 ' Equity to Liability',
 ' Current Liability to Liability',
 ' Equity to Long-term Liability',
 ' Cash Flow Per Share',
 ' total assets to GNP price',
 ' Net Income to Total Assets',
 " Net Income to Stockholder's Equity",
 ' Total Asset Turnover',
 ' Working Capital to Sales',
 ' Cash Flow to Sales',
 ' Cash Flow to Total Assets',
 ' CFO to Assets']

In [94]:
unmatched1

[' Cost of Interest-bearing Debt',
 ' Cash Reinvestment Ratio',
 ' Acid Test',
 ' Interest Expenses/Total Revenue',
 ' Total Liability/Equity Ratio',
 ' Liability/Total Assets',
 ' Interest-bearing Debt/Equity',
 ' Contingent Liability/Equity',
 ' Operating Income/Capital',
 ' Pretax Income/Capital',
 ' Quick Assets/Total assets',
 ' Cash/Total Assets',
 ' Quick Assets/Current Liability',
 ' Cash/Current Liability',
 ' Operating Funds to Liability',
 ' Inventory/Current Liability',
 ' Current Liabilities/Liability',
 ' Current Liabilities/Equity',
 ' Current Liability to Current Assets',
 ' One if Total Liability exceeds Total Assets;',
 ' Equity/Total Assets',
 ' (Long-term Liability+Equity)/Fixed Assets',
 ' Fixed Assets to Assets',
 ' Current Liability to Equity',
 ' Liability to Equity',
 ' Degree of Financial Leverage',
 ' Interest Coverage Ratio',
 ' Operating Expenses/Net Sales',
 ' (Research and Development Expenses)/Net Sales',
 ' Effective Tax Rate',
 ' Book Value Per Share(B)',
 ' Book Value Per Share(A)',
 ' Book Value Per Share(C)',
 ' Sales Per Share',
 ' Operating Income Per Share',
 ' Sales Per Employee',
 ' Operation Income Per Employee',
 ' Fixed Assets Per Employee',
 ' Return On Total Assets(C)',
 ' Return On Total Assets(A)',
 ' Return On Total Assets(B)',
 ' Gross Profit /Net Sales',
 ' Realized Gross Profit/Net Sales',
 ' Operating Income /Net Sales',
 ' Pre-Tax Income/Net Sales',
 ' Net Income/Net Sales',
 ' Net Non-operating Income Ratio',
 ' Net Income-Exclude Disposal Gain or Loss/Net Sales',
 ' EPS-Net Income',
 ' Pretax Income Per Share',
 ' Retained Earnings to Total Assets',
 ' Total Income to Total Expenses',
 ' Total Expenses to Assets',
 ' Gross Profit to Sales',
 ' One if Net Income is Negative for the Last Two Years; Zero Otherwise',
 ' (Inventory +Accounts Receivables) /Equity',
 ' Accounts Receivable Turnover',
 ' Days Receivable Outstanding',
 ' Inventory Turnover',
 ' Fixed Asset Turnover',
 ' Equity Turnover',
 ' Current Assets to Sales',
 ' Quick Assets to Sales',
 ' Cash to Sales',
 ' No-credit Interval',
 ' Cash Flow from Operating/Current Liabilities',
 ' Cash Flow to Liability',
 ' Cash Flow to Equity',
 ' Realized Gross Profit Growth Rate',
 ' Operating Income Growth',
 ' Net Income Growth',
 ' Continuing Operating Income after Tax Growth',
 ' Net Income-Excluding Disposal Gain or Loss Growth',
 ' Total Asset Growth',
 ' Total Equity Growth',
 ' Return on Total Asset Growth']

In [95]:
unmatched2

['Flag',
 'ROA(C) Before tax, before interest, and before depreciation',
 'ROA(A)% after tax',
 'ROA(B) After tax, before interest, before depreciation',
 'Operating gross profit margin',
 'Realized gross profit margin',
 'Operating profit ratio',
 'Net interest rate before tax',
 'Net interest rate after tax',
 'Non-industry revenue and expenditure / revenue',
 'Persistent interest rate (after tax)',
 'Operating expense ratio',
 'Research and development expense rate',
 'Cash flow ratio',
 'Interest-bearing debt interest rate',
 'Tax rate (A)',
 'Net value per share (B)',
 'Net value per share (A)',
 'Net value per share (C)',
 'Persistent EPS in the past four seasons',
 'Turnover per share (yuan)',
 'Operating profit per share (yuan)',
 'Net profit per share before tax (yuan)',
 'Realized sales gross profit growth rate',
 'Operating profit growth rate',
 'After-tax net profit growth rate',
 'Regular net profit growth rate',
 'Continuous net profit growth rate',
 'Total asset growth rate',
 'Net worth growth rate',
 'Total return on assets growth rate',
 'Cash reinvestment%',
 'Quick ratio',
 'Interest expense rate',
 'Total debt/total net worth',
 'Debt ratio%',
 'Net worth/assets',
 'Long-term funding suitability ratio (A)',
 'Borrowing dependence',
 'Contingent liabilities/net worth',
 'Operating profit / paid-in capital',
 'Net profit before tax / paid-in capital',
 'Inventory and accounts receivable/net value',
 'Turnover times of accounts receivable',
 'Average collection days',
 'Inventory turnover rate (times)',
 'Turnover of fixed assets',
 'Net worth turnover rate (times)',
 'Revenue per person',
 'Operating profit per person',
 'Equipped rate per person',
 'Quick asset/Total asset',
 'cash / total assets',
 'Quick asset/current liabilities',
 'cash / current liability',
 'operating funds to liability',
 'Inventory/current liability',
 'current liability / liability',
 'current liability/equity',
 'Retained Earnings/Total assets',
 'total income / total expense',
 'total expense /assets',
 'Liquid assets turnover rate',
 'Quick asset turnover rate',
 'Cash turnover',
 'fix assets to assets',
 'current liability to equity',
 'cash flow to liability',
 'cash flow to equity',
 'current liabilities to current assets',
 'one if total liabilities exceeds total assets  zero otherwise',
 'No-credit interval',
 'Gross profit to Sales',
 'liability to equity',
 'Degree of financial leverage (DFL)',
 'Interest coverage ratio( Interest expense to EBIT )',
 'one if net income was negative for the last two year  zero otherwise']

In [92]:
find_perfect_match([' Cash Flow to Liability'],['cash flow to liability'])

 Cash Flow to Liability
cash flow to liability
______________________________

([' Cash Flow to Liability'], ([], []))